env:
  browser: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-misleading-character-class: off
  no-unused-vars: off
  use-isnan: off
