# -*- mode: docker-compose; -*- vim: set ft=yaml:
version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: convert-coord-dev:latest
    ports:
      - 8080:5173
      - 8081:4173
      - 8090:80
    volumes:
      - type: bind
        source: .
        target: /convert-coord
      - type: volume
        source: web_node_modules
        target: /convert-coord/node_modules

volumes:
  web_node_modules:
